### PR TITLE
Login

### PR DESCRIPTION
**Pull request by ghiobi**
Add login page.
Style to match mockups

### CODE REVIEW

**Review by JTalarico — CHANGES_REQUESTED** [review]
I really don't think we should have username and password. My understanding is that is just for offline, and so we shouldn't have it there unless offline is ready.

Also if you can make the Facebook button[ like this](http://www.freeiconspng.com/free-images/login-button-png-18039) that might be nicer. Not really important though.

**Comment by ghiobi** [comment]
We talked with the client so many times, and even told him that a user can only sign up with a social media account and then can use account credentials to login into mBarter for our offline feature.

**Comment by ghiobi** [comment]
I will add functionality and theming in the next iteration.

**Review by JTalarico — APPROVED** [review]
Pass for now. But this will need to be fixed later.

**Pull request merged**
